version: "3"

services:
  vpncloud:
    build: .

    restart: unless-stopped

    volumes:
      - "./data:/etc/vpncloud:rw"

    environment:
      CONFIG_FILE: "vpncloud.net"

    network_mode: host

    privileged: true
